name: .NET CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x # Use the .NET version your project targets

    - name: Restore dependencies
      run: dotnet restore SimpleNotepad.sln

    - name: Build
      # Build in Debug configuration for CI checks
      run: dotnet build SimpleNotepad.sln --configuration Debug --no-restore

    # If you add unit tests later, uncomment the following step:
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
